import { Product } from "@/types";

export const products: Product[] = [
  {
    id: 1,
    name: "Dark Jacket",
    src: "/products/jacket.jpg",
    price: "69.00",
    new: true,
    men: true,
    outerwear: true,
    date: "2024-06-28",
    salesCount: 15,
    stock: 12,
    description:
      "Stay stylishly warm with this sleek dark jacket. Perfect for any season.",
    keywords: [
      "dark jacket",
      "jacket",
      "outerwear",
      "men jacket",
      "black jacket",
      "men",
    ],
  },
  {
    id: 2,
    name: "Chino Bottoms",
    src: "/products/bottoms.jpg",
    price: "99.00",
    sale: true,
    discountPrice: "69.00",
    new: true,
    men: true,
    bottom: true,
    date: "2024-06-27",
    salesCount: 20,
    stock: 23,
    description:
      "Versatile and comfortable, perfect for any occasion. Elevate your casual look.",
    keywords: [
      "chino bottoms",
      "chino pants",
      "bottoms",
      "men pants",
      "casual pants",
      "men",
    ],
  },
  {
    id: 3,
    name: "Brown Shoe",
    src: "/products/shoe.jpg",
    price: "29.00",
    sale: false,
    men: true,
    footwear: true,
    date: "2024-06-15",
    salesCount: 8,
    stock: 18,
    description:
      "Classic brown shoes that match every outfit. Timeless style and comfort.",
    keywords: [
      "brown shoe",
      "shoes",
      "footwear",
      "men shoes",
      "classic shoes",
      "men",
    ],
  },
  {
    id: 4,
    name: "The Modern Sock",
    src: "/products/sock.jpg",
    price: "29.00",
    men: true,
    footwear: true,
    date: "2024-06-10",
    salesCount: 12,
    stock: 15,
    description:
      "Step into comfort with these modern socks. A perfect addition to your wardrobe.",
    keywords: [
      "modern socks",
      "socks",
      "footwear",
      "men socks",
      "comfortable socks",
      "men",
    ],
  },
  {
    id: 5,
    name: "Double Knit Sweater",
    src: "/products/sweater.jpg",
    price: "99.00",
    sale: true,
    discountPrice: "69.00",
    men: true,
    top: true,
    date: "2024-06-18",
    salesCount: 32,
    stock: 35,
    description: "Double the knit, double the warmth. Cozy up in style.",
    keywords: [
      "double knit sweater",
      "sweater",
      "top",
      "men sweater",
      "warm sweater",
      "men",
    ],
  },
  {
    id: 6,
    name: "The Murray",
    src: "/products/watch.jpg",
    price: "99.00",
    sale: true,
    discountPrice: "69.00",
    men: true,
    accessories: true,
    date: "2024-06-18",
    salesCount: 25,
    stock: 28,
    description:
      "Timeless elegance in a modern design. Perfect for any occasion.",
    keywords: [
      "Murray watch",
      "watch",
      "accessories",
      "men watch",
      "elegant watch",
      "men",
    ],
  },
  {
    id: 7,
    name: "Cream Jacket",
    src: "/products/jacket-4.png",
    price: "99.00",
    new: true,
    women: true,
    outerwear: true,
    date: "2024-06-29",
    salesCount: 10,
    stock: 14,
    description:
      "Chic and cozy, this cream jacket is a must-have. Elevate your outerwear collection.",
    keywords: [
      "cream jacket",
      "jacket",
      "outerwear",
      "women jacket",
      "chic jacket",
      "women",
    ],
  },
  {
    id: 8,
    name: "Plain Jeans",
    src: "/products/bottoms-3.png",
    price: "69.00",
    women: true,
    bottom: true,
    date: "2024-06-12",
    salesCount: 5,
    stock: 11,
    description:
      "Classic jeans for effortless style. Versatile and comfortable.",
    keywords: [
      "plain jeans",
      "jeans",
      "bottoms",
      "women jeans",
      "classic jeans",
      "women",
    ],
  },
  {
    id: 9,
    name: "Formal Sandals",
    src: "/products/shoe-3.png",
    price: "29.00",
    women: true,
    footwear: true,
    date: "2024-06-08",
    salesCount: 7,
    stock: 13,
    description:
      "Elegant sandals for a formal touch. Step into sophistication.",
    keywords: [
      "formal sandals",
      "sandals",
      "footwear",
      "women sandals",
      "elegant sandals",
      "women",
    ],
  },
  {
    id: 10,
    name: "Wool Sock",
    src: "/products/sock-3.png",
    price: "49.00",
    sale: true,
    discountPrice: "29.00",
    new: true,
    women: true,
    footwear: true,
    date: "2024-06-30",
    salesCount: 35,
    stock: 40,
    description:
      "Cozy up with these premium wool socks. Warmth and comfort guaranteed.",
    keywords: [
      "wool socks",
      "socks",
      "footwear",
      "women socks",
      "warm socks",
      "women",
    ],
  },
  {
    id: 11,
    name: "Comfy Wool Sweater",
    src: "/products/sweater-3.jpg",
    price: "99.00",
    new: true,
    women: true,
    top: true,
    date: "2024-06-26",
    salesCount: 16,
    stock: 17,
    description:
      "Stay warm and stylish with this comfy wool sweater. Perfect for chilly days.",
    keywords: [
      "comfy wool sweater",
      "sweater",
      "top",
      "women sweater",
      "warm sweater",
      "women",
    ],
  },
  {
    id: 12,
    name: "Vintage Timepiece",
    src: "/products/watch-2.jpg",
    price: "99.00",
    sale: true,
    discountPrice: "69.00",
    new: true,
    women: true,
    accessories: true,
    date: "2024-06-24",
    salesCount: 22,
    stock: 24,
    description:
      "Add a touch of vintage charm to your look. Classic design with a modern twist.",
    keywords: [
      "vintage watch",
      "watch",
      "timepiece",
      "accessories",
      "women watch",
      "classic watch",
      "women",
    ],
  },
  {
    id: 13,
    name: "Formal White Shirt",
    src: "/products/shirt-1.jpg",
    price: "39.00",
    new: true,
    men: true,
    top: true,
    date: "2024-06-23",
    salesCount: 9,
    stock: 19,
    description:
      "Sharp and clean, perfect for formal occasions. A wardrobe essential.",
    keywords: [
      "formal white shirt",
      "shirt",
      "top",
      "men shirt",
      "formal shirt",
      "men",
    ],
  },
  {
    id: 14,
    name: "Modern Jacket",
    src: "/products/jacket-3.png",
    price: "69.00",
    new: true,
    men: true,
    outerwear: true,
    date: "2024-06-22",
    salesCount: 11,
    stock: 21,
    description: "A modern jacket for a modern man. Stylish and practical.",
    keywords: [
      "modern jacket",
      "jacket",
      "outerwear",
      "men jacket",
      "stylish jacket",
      "men",
    ],
  },
  {
    id: 15,
    name: "Green Cargo Shorts",
    src: "/products/bottoms-2.jpg",
    price: "99.00",
    new: true,
    men: true,
    bottom: true,
    date: "2024-06-25",
    salesCount: 30,
    stock: 34,
    description:
      "Casual and practical, these cargo shorts are a staple. Perfect for everyday wear.",
    keywords: [
      "green cargo shorts",
      "cargo shorts",
      "bottoms",
      "men shorts",
      "casual shorts",
      "men",
    ],
  },
  {
    id: 16,
    name: "Classy Black Shoe",
    src: "/products/shoe-2.jpg",
    price: "49.00",
    new: true,
    men: true,
    footwear: true,
    date: "2024-06-21",
    salesCount: 13,
    stock: 20,
    description:
      "Elegant black shoes for every occasion. Timeless and versatile.",
    keywords: [
      "classy black shoes",
      "black shoes",
      "footwear",
      "men shoes",
      "elegant shoes",
      "men",
    ],
  },
  {
    id: 17,
    name: "Classic Calf Socks",
    src: "/products/sock-4.jpg",
    price: "29.00",
    men: true,
    footwear: true,
    date: "2024-06-20",
    salesCount: 10,
    stock: 17,
    description:
      "Classic calf socks for ultimate comfort. A wardrobe essential.",
    keywords: [
      "classic calf socks",
      "calf socks",
      "socks",
      "men socks",
      "comfortable socks",
      "men",
    ],
  },
  {
    id: 18,
    name: "Classic Cozy Sweater",
    src: "/products/sweater-2.jpg",
    price: "69.00",
    men: true,
    top: true,
    date: "2024-06-11",
    salesCount: 3,
    stock: 16,
    description: "Cozy up in this classic sweater. Perfect for chilly days.",
    keywords: [
      "classic cozy sweater",
      "cozy sweater",
      "sweater",
      "men sweater",
      "warm sweater",
      "men",
    ],
  },
  {
    id: 19,
    name: "The Modern Watch",
    src: "/products/watch-3.jpg",
    price: "99.00",
    new: true,
    men: true,
    accessories: true,
    date: "2024-06-19",
    salesCount: 19,
    stock: 27,
    description:
      "Sleek and modern, this watch is a statement piece. Elevate your look.",
    keywords: [
      "modern watch",
      "watch",
      "accessories",
      "men watch",
      "sleek watch",
      "men",
    ],
  },
  {
    id: 20,
    name: "Urban Jacket",
    src: "/products/jacket-2.jpg",
    price: "69.00",
    women: true,
    outerwear: true,
    date: "2024-06-13",
    salesCount: 8,
    stock: 14,
    description: "Urban chic with this stylish jacket. Stay warm and trendy.",
    keywords: [
      "urban jacket",
      "jacket",
      "outerwear",
      "women jacket",
      "chic jacket",
      "women",
    ],
  },
  {
    id: 21,
    name: "Effortless Style Jeans",
    src: "/products/bottoms-4.png",
    price: "99.00",
    sale: true,
    discountPrice: "69.00",
    women: true,
    bottom: true,
    date: "2024-06-17",
    salesCount: 27,
    stock: 32,
    description:
      "Jeans that offer effortless style and comfort. A perfect fit for any look.",
    keywords: [
      "effortless style jeans",
      "jeans",
      "bottoms",
      "women jeans",
      "comfortable jeans",
      "women",
    ],
  },
  {
    id: 22,
    name: "Elegant Formal Heels",
    src: "/products/shoe-4.jpg",
    price: "29.00",
    women: true,
    footwear: true,
    date: "2024-06-09",
    salesCount: 4,
    stock: 13,
    description:
      "Step up your style with these elegant heels. Perfect for formal occasions.",
    keywords: [
      "elegant formal heels",
      "formal heels",
      "heels",
      "women heels",
      "elegant heels",
      "women",
    ],
  },
  {
    id: 23,
    name: "Classic Knit Socks",
    src: "/products/sock-2.jpg",
    price: "29.00",
    new: true,
    women: true,
    footwear: true,
    date: "2024-06-31",
    salesCount: 7,
    stock: 16,
    description:
      "Keep it classic with these knit socks. Comfortable and stylish.",
    keywords: [
      "classic knit socks",
      "knit socks",
      "socks",
      "women socks",
      "comfortable socks",
      "women",
    ],
  },
  {
    id: 24,
    name: "Elegant Comfort Sweater",
    src: "/products/sweater-4.png",
    price: "99.00",
    new: true,
    women: true,
    top: true,
    date: "2024-06-29",
    salesCount: 29,
    stock: 39,
    description:
      "Elegance meets comfort in this stylish sweater. Perfect for any occasion.",
    keywords: [
      "elegant comfort sweater",
      "comfort sweater",
      "sweater",
      "women sweater",
      "stylish sweater",
      "women",
    ],
  },
  {
    id: 25,
    name: "Classic Silver Watch",
    src: "/products/watch-4.jpg",
    price: "99.00",
    new: true,
    women: true,
    accessories: true,
    date: "2024-06-28",
    salesCount: 14,
    stock: 28,
    description:
      "A classic silver watch for a timeless look. Perfect for any outfit.",
    keywords: [
      "classic silver watch",
      "silver watch",
      "watch",
      "women watch",
      "timeless watch",
      "women",
    ],
  },
  {
    id: 26,
    name: "Classic Green Shirt",
    src: "/products/shirt-2.jpg",
    price: "49.00",
    sale: true,
    discountPrice: "29.00",
    men: true,
    top: true,
    date: "2024-06-16",
    salesCount: 9,
    stock: 20,
    description:
      "Refresh your wardrobe with this classic green shirt. A staple for any occasion.",
    keywords: [
      "classic green shirt",
      "green shirt",
      "shirt",
      "top",
      "men shirt",
      "men",
    ],
  },
];

export function countProducts(products: Product[]) {
  const counts = {
    idCount: 0,
    newCount: 0,
    menCount: 0,
    womenCount: 0,
    topCount: 0,
    bottomCount: 0,
    footwearCount: 0,
    acceCount: 0,
    outerwearCount: 0,
  };

  products.forEach((product) => {
    if (product.id) counts.idCount++;
    if (product.new) counts.newCount++;
    if (product.men) counts.menCount++;
    if (product.women) counts.womenCount++;
    if (product.top) counts.topCount++;
    if (product.bottom) counts.bottomCount++;
    if (product.footwear) counts.footwearCount++;
    if (product.accessories) counts.acceCount++;
    if (product.outerwear) counts.outerwearCount++;
  });

  return counts;
}

const {
  idCount,
  newCount,
  menCount,
  womenCount,
  topCount,
  bottomCount,
  footwearCount,
  acceCount,
  outerwearCount,
} = countProducts(products);

export const categoryStatus = [
  { label: "All", count: idCount },
  { label: "New", count: newCount },
  { label: "Men", count: menCount },
  { label: "Women", count: womenCount },
  { label: "Top", count: topCount },
  { label: "Bottom", count: bottomCount },
  { label: "Footwear", count: footwearCount },
  { label: "Accessories", count: acceCount },
  { label: "Outerwear", count: outerwearCount },
];
